name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          flutter-version: '3.24.0'
      - name: Inject Google Services Configuration
        run: |
          # تأكيد اسم الحزمة ليتطابق مع ملف الـ JSON
          flutter create . --platforms android --org com.starchat --project-name starchat_love
          
          # ربط ملف google-services.json بملفات الأندرويد برمجياً
          sed -i '/dependencies {/a \        classpath "com.google.gms:google-services:4.3.15"' android/build.gradle
          echo "apply plugin: 'com.google.gms.google-services'" >> android/app/build.gradle
          
          flutter pub get
      - name: Build Official APK
        run: flutter build apk --release --no-tree-shake-icons
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Starchat-Love-Ready
          path: build/app/outputs/flutter-apk/app-release.apk
